### ISSUE TITLE
Lack of one space in 202 line of "ina226.py" file

### ISSUE THREAD

**Issue by leszekwawrzonkowski** [elschopi/TI_INA226_micropython#1]
Hi,
I've tried to use this great library and have got an error:
  File "ina226.py", line 202
IndentationError: unindent doesn't match any outer indent level

When I add a missing space in line 202 it works fine :)

Best regards and thanks for this library :)

**Comment by elschopi** [comment]
Thanks for noticing! Don't know why it never gave me any problems, but now it should be fixed!
